### ISSUE TITLE
Current Status of Project?

### ISSUE THREAD

**Issue by dhufnagel** [t1/problem-details#42]
Hi,

I'd like to build the project for jaxrs but did not manage to do so. I came across the issue, that the master branch relies on a class of the sandbox api, which is not there. The class ResponseStatus does not exist. So how could this project be build? I started to migrate to javax.ws.rs.core.Response.Status and have all files in my own project. 

So I wanted to ask, what the current status of this project is? Is it supposed to be that way or am I doing something wrong?

**Comment by t1** [comment]
I didn't notice that, because the GitHub Actions pass. I'll investigate.

As for the status: the latest release is ready to use, while the move to MicroProfile in a sort of hibernation, i.e. I currently have too many other things to attend to (mainly MP GraphQL). I take your question as an indication that I should try to get back to it soon and finish my stuff ;-) Thanks for the support :-)

**Comment by t1** [comment]
You need to build https://github.com/t1/microprofile-sandbox first. I'm working on getting that into upstream, so it's sufficient to build https://github.com/eclipse/microprofile-sandbox

**Comment by amoscatelli** [comment]
Any news ? What do I have to do so use this spec in my project ?
I can't find the dependencies on any maven server ...

**Comment by t1** [comment]
@amoscatelli: I hardly got any feedback on this, so I thank you for yours. I'm not getting paid for this, so I can't promise anything. But it would help me, if you could tell a little bit more about the setting you want to use it in.

**Comment by amoscatelli** [comment]
Sorry I am not sure I understood your question.
I want my backend to use the RFC-7807 specification to handle errors.
I just wanted to download the last dependencies (the one implementing the microprofile problem details proposal API) without compiling it myself.

**Comment by t1** [comment]
I've released version 1.0.9 to Maven Central. The 2.x branch is in an unfinished state. HTH. Questions welcome!
